spring.application.name=cruddemo

spring.datasource.url=jdbc:postgresql://localhost:5432/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#Turn off the Spring banner
spring.main.banner-mode=off

# Reduce loggin level. Set loggin level to warn
logging.level.root=warn
